Repository ECDAR-AAU-SW-P5/Ecdar-API, pull requests merged in 2023-12, with the labels that each got.

#68 Implement update model endpoint
  src/api/ecdar_api.rs
  src/database/in_use_context.rs
  src/database/model_context.rs
  src/tests/api/model_logic.rs
  src/tests/database/access_context.rs
  src/tests/database/in_use_context.rs
Labels: documentation, enhancement, A$AP, ROCKY

#74 list_access_info endpoint + delete_session + Implement role checking in access endpoints
  src/api/ecdar_api.rs
  src/tests/api/session_logic.rs
Labels: A$AP, ROCKY

#94 92 testing reveaal service
  src/main.rs
  src/services/service_impls/reveaal_service.rs
  src/tests/mod.rs
  src/tests/services/mod.rs
  src/tests/services/reveaal_service.rs
Labels: enhancement, question
