Repository ECDAR-AAU-SW-P5/Ecdar-API, pull requests merged in 2023-11, with the labels that each got.

#11 2 define interface for database
  .env.example
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  README.md
  api_server/Cargo.toml
  api_server/src/main.rs
  database/Cargo.toml
  database/src/lib.rs
  migration/src/lib.rs
  migration/src/m20231012_094213_create_user_table.rs
  migration/src/m20231012_094228_create_model_table.rs
  migration/src/m20231012_094242_create_query_table.rs
  migration/src/m20231012_094303_create_in_use_table.rs
  migration/src/m20231012_094422_create_session_table.rs
  migration/src/m20231012_094533_create_access_table.rs
  migration/src/m20231012_122243_create_role_type.rs
  migration/src/main.rs
  src/api/mod.rs
  src/database/access_context.rs
  src/database/database_context.rs
  src/database/entity_context.rs
  src/database/in_use_context.rs
  src/database/mod.rs
  src/database/model_context.rs
  src/database/query_context.rs
  src/database/session_context.rs
  src/database/user_context.rs
  src/entities/access.rs
  src/entities/in_use.rs
  src/entities/mod.rs
  src/entities/model.rs
  src/entities/prelude.rs
  src/entities/query.rs
  src/entities/sea_orm_active_enums.rs
  src/entities/session.rs
  src/entities/user.rs
  src/main.rs
  src/tests/database/access_context.rs
  src/tests/database/helpers.rs
  src/tests/database/in_use_context.rs
  src/tests/database/mod.rs
  src/tests/database/model_context.rs
  src/tests/database/query_context.rs
  src/tests/database/session_context.rs
  src/tests/database/user_context.rs
  src/tests/mod.rs
Labels: documentation, enhancement

#63 58 refactor reveaal and user endpoint tests
  .github/workflows/test.yml
  src/api/context_collection.rs
  src/api/ecdar_api.rs
  src/api/hashing_context.rs
  src/api/mod.rs
  src/api/server.rs
  src/database/access_context.rs
  src/database/in_use_context.rs
  src/database/model_context.rs
  src/database/query_context.rs
  src/database/session_context.rs
  src/database/user_context.rs
  src/main.rs
  src/tests/api/access_logic.rs
  src/tests/api/ecdar_api.rs
  src/tests/api/helpers.rs
  src/tests/api/query_logic.rs
  src/tests/api/session_logic.rs
  src/tests/api/user_logic.rs
  src/tests/database/access_context.rs
  src/tests/database/in_use_context.rs
  src/tests/database/model_context.rs
  src/tests/database/query_context.rs
  src/tests/database/session_context.rs
  src/tests/database/user_context.rs
Labels: ASAP

#65 Implement create model endpoint
  Cargo.toml
  migration/src/m20231012_094228_create_model_table.rs
  src/api/ecdar_api.rs
  src/build.rs
  src/database/access_context.rs
  src/database/model_context.rs
  src/database/session_context.rs
  src/tests/api/helpers.rs
  src/tests/api/model_logic.rs
  src/tests/api/session_logic.rs
  src/tests/database/access_context.rs
  src/tests/database/helpers.rs
  src/tests/database/in_use_context.rs
  src/tests/database/model_context.rs
  src/tests/database/session_context.rs
Labels: enhancement, A$AP
